---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-node1
  namespace: labo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-node1
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-node2
  namespace: labo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-node2
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50