---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-html
  template:
    metadata:
      labels:
        app: hello-html
    spec:
      containers:
        - name: hello-html
          image: hello-html:1.0
          imagePullPolicy: Never    # image locale, ne pas chercher sur Docker Hub
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-html
spec:
  selector:
    app: hello-html
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090              # port accessible depuis l'extérieur du cluster